# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Checks

env:
  RAILS_ENV: test
  PGHOST: 127.0.0.1
  PGUSER: postgres
  PGDATABASE: prace_dyplomowe_test
  PGPASSWORD: postgres

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  build:
    name: Run Checks

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true
    - name: Run linter
      run: bundle exec rubocop           
    - name: Setup database
      run: bundle exec rails db:test:prepare
    - name: Run specs
      run: |
        # export DISPLAY=:99
        # chromedriver --url-base=/wd/hub &
        # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        bundle exec rspec --exclude-pattern 'spec/system/**/*_spec.rb'